# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'README'
  link: 'README'
- label: 'Books'
  items:
    - label: '프로그래머의 뇌'
      link: '/Books/프로그래머의-뇌'
    - label: 'git-cheatsheet'
      link: '/Git/git-cheatsheet'
    - label: 'Top-level-domain'
      link: '/Network/Top-level-domain'
- label: 'Python/os_module'
  link: '/Python/os_module'
- label: 'More'
  items:
    - label: 'Github'
      link: https://github.com/jpedroschmitz/rocketdocs
